name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: registry.gitlab.steamos.cloud/steamrt/sniper/sdk:latest
    steps:
      - name: Checkout plugin
        uses: actions/checkout@v4
        with:
          path: MapChooser

      - name: Checkout dependencies
        run: |
          git clone --depth 1 https://github.com/Pisex/SchemaEntity.git SchemaEntity
          git clone --depth 1 --recurse-submodules https://github.com/alliedmodders/metamod-source.git mmsource
          git clone --depth 1 -b cs2 https://github.com/Pisex/hl2sdk.git hl2sdk-cs2
          git clone --depth 1 https://github.com/alliedmodders/ambuild.git ambuild

      - name: Install AMBuild
        run: |
          python3 -m pip install ./ambuild || pip3 install ./ambuild

      - name: Build
        working-directory: MapChooser
        run: |
          mkdir build && cd build
          python3 ../configure.py --plugin-name=MapChooser --plugin-alias=map_chooser \
            --hl2sdk-manifests=../hl2sdk-manifests --hl2sdk-root="$GITHUB_WORKSPACE" \
            --mms_path="$GITHUB_WORKSPACE/mmsource" --sdks=cs2 --targets=x86_64 --enable-optimize
          ambuild

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: MapChooser-linux
          path: MapChooser/build/package
